language: node_js

os:
  - linux
  - windows

dist: xenial
arch: amd64

cache: npm

node_js:
  - 10
  - 12
  - 13
  - node    # Always include latest stable
  - lts/*   # Always include latest LTS

notifications:
  email: false
  slack:
    rooms:
      - secure: eeujEPADw5Mu/ZkhyP6Ppj9xjPWh5qPbe6j2f29THZjlpIq2F9vCDsqtqJlvr7tom2WCsgIQT05yDY8yvc8DYEgaEkqF0U2BJ01XlUscVON6GaD3+Qhn9rxSJnJsfRVH0c417IO9ystliMrz4nMcE7Q6HhsCB61JTJ5t4Osi03VhNm40NyB8MouBSQKnPeAoZgJRiset2v+TrN2FO1Jm8el9m3uRxqaV1QWK609byAl0BYGxCZaly8HXMTlmJPXSOAv/gZH0O5sA4y9VrZYm+u/g7G5fi+CUfzuJUU1tgCtTK3hxiIUn/MDUDeHBz5LKYG8qQHUO+yGdD6mQVpzgiRlF83V60UFxpZgVh5ENuvNhFyxe/9x6ORjcrcSfNFk3gO50u59s58wqcvSxTRyx89xuVF9fDoxialD9vdo8xjEuEXCo+JZ+HQtwfHNp0b3nnPGQpgo+MMZQeWWPg5S1FsvJotutsuj0Nuq/lUQSsH7DjLOnzsXFOGv0rUrW/dE/s6OEYdIV0t4q6AagHCOlmjPDVTtOMEQZtb3tSv6sqvA6ogvgrjpFLeDqCZjuiJ9mUqzG+6hy4EhoINXGSEW1OF7q5mTcjCXwjfajxIdtSlj9kPctSAt605SdYgCD9GH2MTEmqCit1v2wndzJkwBsGESmKkvpwLoi4CwSmvbF0/4=
    on_success: change
    on_failure: always
